Address build issues on Ubuntu 22.04
- Update `m4/ac_python_devel.m4` to support Pythn 3.10 on Ubuntu 22.04
- Update `m4/python.m4` to support Python 3.10 on Ubuntu 22.04
- Add libtirpc link dependency to dsosd. Without libtirpc, dsosd build
  results in an error "undefined reference to symbol 'xdr_free'".
  `xdr_free()` is directly called in `sosapi_server.c`, hence a need to
  resolve `xdr_free()` on Ubuntu 22.04 (libtools on CentOS 7 allows
  unresolved symbols at link/build time).